"""add fields to story model

Revision ID: 124dd29824ec
Revises: 27dd810b88d6
Create Date: 2024-03-05 09:01:57.827477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124dd29824ec'
down_revision: Union[str, None] = '27dd810b88d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('name', sa.String(length=255), server_default='', nullable=False))
    op.add_column('story', sa.Column('story_type', sa.Enum('install', 'update', 'info', native_enum=False), server_default='info', nullable=False))
    op.add_column('story', sa.Column('delay', sa.Integer(), nullable=True))
    op.add_column('story', sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('story', sa.Column('is_blocking', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('story', sa.Column('is_preview', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('story', sa.Column('is_repetitive', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('story', sa.Column('is_autoscroll', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('story', sa.Column('publication_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('story', sa.Column('publication_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'publication_end_time')
    op.drop_column('story', 'publication_start_time')
    op.drop_column('story', 'is_autoscroll')
    op.drop_column('story', 'is_repetitive')
    op.drop_column('story', 'is_preview')
    op.drop_column('story', 'is_blocking')
    op.drop_column('story', 'is_disabled')
    op.drop_column('story', 'delay')
    op.drop_column('story', 'story_type')
    op.drop_column('story', 'name')
    # ### end Alembic commands ###
